export const constantes = {
    JWT_TOKEN:'SDJ_TOKEN',
    TOKEN_LEVEL: 'SDJ_TK_LVL',
    TOKEN_VALID_SEC: 'SDJ_EXP',
    REFRESH_TOKEN_VALID_SEC: 'SDJ_REF',
    DATETIME_NEW_TOKEN:'SDJ_TNT',

    USUARIO: 'USR_SDJ',
    USUARIO_OPCIONES: 'USR_SDJ_OP',
    USUARIO_PERFIL: 'USR_SDJ_PE',
    //-- NIVELES DE TOKEN
    TOK_LVL_AUTH: 'USR_SDJ_TL_AUTH',
    TOK_LVL_LOGIN: 'USR_SDJ_TL_LGN',
    TOK_LVL_OPCIONES: 'USR_SDJ_TL_OPT',    
    //-- RESPONSE CODIGOS
    RESPONSE_COD_EXITO:'0000'
}